config/routes.rb
Dd3::Application.routes.draw do

  resources :site do
    collection do
      get 'index'
      get 'info'
      get 'signin'
      get 'privacy'
      get 'blog'
      get 'faq'
      get 'about'
    end
  end
  
  resources :deals do
   collection do
    post 'order_deals'
    get 'index_deals'
    get 'scenario'
    post 'create_new_scenario'
    get 'index_first_page'
    get 'index_last_page'
    get 'index_previous_page'
    get 'index_next_page'
    get 'delete_random_deals'
   end
  end  

  resources :reps do
    resources :deals
    get 'order_reps', :on => :collection
    get 'rank_reps', :on => :collection
  end
  
  resources :regions do
    resources :reps
    get 'order_regions', :on => :collection
  end
  
  resources :histories do
    resources :reps
  end
  
  resources :home
  
  resources :analytics do
    collection do
      get 'summarize_deals'
      get 'summarize_all_reps'
      get 'summarize_all_regions'
      get 'summarize_this_rep'
      get 'summarize_this_region'
      get 'simulate_parameters'
      get 'chart_pdf_cdf'
      get 'chart_likely_histo'
      get 'chart_prob_histo'
      get 'chart_achieved_vs_x'
      get 'chart_achieved_vs_forecast'
      get 'chart_achieved_vs_pipeline'
    end
  end
    
  resources :express do
    collection do
      post 'upload_file'
    end
  end
  
  resources :customers
  
  resources :scenarios
  
  resources :users
  resources :admin
  
  resources :sessions do
    collection do
      get 'signin_success'
      get 'signout_success'
    end
  end

  root :to => 'site#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/analytics_controller.rb
# Copyright © by David M. Spenhoff. All rights reserved.


require "visualization"		# charts 
require "summary"					# summaries 
require "simulation"			# simulations
require "regression"      # linear regressions

class AnalyticsController < ApplicationController
  
  before_filter :login_required
  
  def index
    @page_title = 'Analytics'
  end
  
  #
  # methods for summaries
  #
  
  # summarizes all deals 
  def summarize_deals
    @deals = Deal.all
    @show_predicted = false
    summarize_all(filtered_deals("", "all", @deals))
    flash.now[:notice] = "Summary for all open deals"
    @page_title = "Analytics > Summarize deals"
  end
  
  def summarize_all(deals)
    # get the non-simulated summary
    @sum = Summary.new
    @sum.summarize(deals)
    # get the basic simulated summary 
    @sim = Simulation.new
    @sim.simulate(deals, 'dist', 'given', nil, 1.0, nil, nil, nil)
  end
  
  # rep by rep summary of deals
  def summarize_all_reps
    summarize_by(Rep)
    @source = "rep"
    @page_title = "Analytics > Summarize reps"
    render "summarize_by"
  end
  
  #region by region summary of deals
  def summarize_all_regions
    summarize_by(Region)
    @source = "region"
    @page_title = "Analytics > Summarize regions"
    render "summarize_by"
  end
  
  def summarize_by(source)
    # source is Rep or Region
    # iterate source creating a summary object for the deals of each 
    # when complete, @source_all will be either Rep.all or Region.all
    # and @summary_all will contain each of the (rep or region) summaries   
    @summaries = Array.new
    @sources = source.all
    @sources.each do |s|
      sum = Summary.new
      sum.summarize(filtered_deals("", "all", s.deals))
      @summaries << sum
    end    
  end
  
  # summarize the deals for the rep given by params[:id]
  def summarize_this_rep
    rep = Rep.find(params[:id])
    @deals = filtered_deals("", "all", rep.deals)
    summarize_all(@deals)
    @sum.predicted = rep.amount_predicted_regression(:forecast_and_pipeline)[:value]
    @show_predicted = true
    @page_title = "Analytics > Summarize rep"
    flash.now[:notice] = "Summary for rep " + rep.name
    render "summarize_deals"
  end  
  
  # summarize the deals for the region given by params[:id]
  def summarize_this_region
    region = Region.find(params[:id])
    @deals = filtered_deals("", "all", region.deals)
    summarize_all(@deals)
    @sum.predicted = region.amount_predicted_regression
    @show_predicted = true
    @page_title = "Analytics > Summarize region"
    flash.now[:notice] = "Summary for region " + region.name
    render "summarize_deals"
  end
  
  #
  # methods for simulations
  #     
  
  # get parameters for the simulation
  def simulate_parameters
    @reps = Rep.all
    @regions = Region.all
    @page_title = "Analytics > Simulation parameters"
  end
  
  # simulates the deals 
  def simulate_deals 
    
    # set up the simulation parameters
    
    if params[:deal_scope] == 'rep'   
      @deals = Rep.find(params[:rep_scope][:rep_id]).deals
    elsif params[:deal_scope] == 'region'
      @deals = Region.find(params[:region_scope][:region_id]).deals
    else
      @deals = Deal.all
    end
    
    factor = case params[:deal_probability]
             when "set" 
               params[:set_probability].to_f
             when "scaled" 
               params[:scaled_probability].to_f
             else 
               nil
             end
    
    objective = params[:deal_objective]                 
    mode = params[:deal_probability]
    target = params[:target_forecast] == "" ? nil : params[:target_forecast].to_f
    min = params[:min_forecast] == "" ? nil : params[:min_forecast].to_f
    max = params[:max_forecast] == "" ? nil : params[:max_forecast].to_f
    value = params[:scale_values] == "" ? 1.0 : params[:scale_values].to_f
    
    # do the simulation
    @sim = Simulation.new    
    @sim.simulate(filtered_deals(params[:limit_probability], params[:forecast_scope], @deals), objective, mode, factor, value, target, min, max)

    # prepare the charts
    
    if @sim.status == "ok" 
   		# prepare the probability functions url string for google charts from simulation data
    	vis = Visualization.new
    	vis.set_title("Deal statistics with " + @sim.selected_count.to_s + " of " + @deals.length.to_s + " deals selected")
    	vis.make_probability_functions_chart(@sim.pdf, @sim.cdf, @sim.mean)
    	@pf_vis = vis.get_url
      flash.now[:notice] = "Simulation finished: " + @sim.selected_count.to_s + " deals, " + @sim.iterations.to_s + " samples in " + @sim.elapsed_time.to_s + " msecs"
	  else
	    flash.now[:notice] = "Simulation aborted - please check parameters"
    end
  	
    @page_title = "Analytics > Simulate deals"
  end
  
  # charts the pdf and cdf functions 
  def chart_pdf_cdf
   	@page_title = "Analytics > Simulated probability functions"
  	@pf_vis = params[:vis]
  end
  
  #
  # methods for the direct charts
  #
  
  # charts the most likely values in histogram format
  def chart_likely_histo
    @page_title = "Analytics > Most likely values"
    @mlv_histo_vis = Visualization.new.make_most_likely_chart_histo(Deal.all)
  end

  # charts the win probabilities in histogram format  
  def chart_prob_histo
    @page_title = "Analytics > Stages/win probabilities"
    @p_histo_vis = Visualization.new.make_prob_chart_histo(Deal.all)
  end
  
  # charts the achieved results vs. 'x' either the forecasts or the pipelines
  def chart_achieved_vs_x 
    @filter_avx_by = params[:filter_avx_by]
    @avx_type = params[:avx_type]
    
    # make the filtered histories array according to the parameter
    case @filter_avx_by
    when "show_region"
      # use all rep histories for the given region
      filtered_histories = Array.new
      if params[:region_select][:id] != ""
        @selected_region = Region.find(params[:region_select][:id])
      else
        # defaults to first region is show_region is clicked 
        # but a region is not selected
        @selected_region = Region.first
        flash.now[:notice] = "You did not select a region, so used 'first' region. Please select a region."
      end
      @selected_region.reps.each do |rep|
        rep.histories.each do |history|
          filtered_histories << history
        end
      end
      @scope = "region: " + @selected_region.name
    when "show_rep"
      # use all histories for the given rep
      if params[:rep_select][:id] != ""
        @selected_rep = Rep.find(params[:rep_select][:id])
      else
        # defaults to first rep is show_region is clicked 
        # but a rep is not selected
        @selected_rep = Rep.first
        flash.now[:notice] = "You did not select a rep, so used 'first' rep. Please select a rep."
      end      
      filtered_histories = @selected_rep.histories.all
      @scope = "rep: " + @selected_rep.name
    else
      # default: use all histories
      filtered_histories = History.all
      @scope = "all"
    end
    
    # @filter_avx_by = "show_all"   # reset to keep the filter select clean

    # make the achieved and forecasts arrays and pass to visualization method
    # aggregate_histories parameter set in view check box
    @aggregate_histories_checked = (params[:aggregate_histories] == "1") ? true : false   # used in the view
    if @aggregate_histories_checked 
      # aggregate 
      ax_hash = aggregate_histories(filtered_histories)
      a = ax_hash[:achieveds]
      x = @avx_type == 'forecast' ? ax_hash[:forecasts] : ax_hash[:pipelines]
    else
      # don't aggregate
      a = filtered_histories.collect{ |history| history.amount_achieved }
      x = @avx_type == 'forecast' ? filtered_histories.collect{ |history| history.amount_forecast } : filtered_histories.collect{ |history| history.amount_pipeline }
    end

    avx = Visualization.new
    avx.set_title("Achieved Results vs. " + @avx_type.humanize + "($1,000s)")
    if @avx_type == 'forecast'
      @avx_vis = avx.make_chart_achieved_vs_x(a, x, 'Forecast', 1.0)
    else
      @avx_vis = avx.make_chart_achieved_vs_x(a, x, 'Pipeline', 2.5)
    end  
        
    # for use in the view filter selects
    @reps = Rep.all
    @regions = Region.all

    # get the linear regression theta (angle to 45-degree true forecast line)
    # note: must have more than one data point for this
    if a.length > 1
      r = Regression.new
      r.lr(x.collect { |e| [e] }, a, true)
      @theta = (@avx_type == 'forecast' ? r.theta_m_degrees(1.0).round : r.theta_m_degrees(0.4).round)
    else
      @theta = nil
    end
    
    @page_title = "Analytics > Achieved results vs. " + params[:avx_type]
  end
  
  
  # aggregates the given histories by rep
  # e.g., returns a new array with entries for each rep that sums that rep's achieveds and forecasts
  # can't assume the given histories array is sorted in any order
  def aggregate_histories(histories)
    # sort histories by rep_id (ascending or descending does not matter)
    sorted = histories.length.times.collect{ |i| [histories[i].rep_id, i] }.sort!
    sorted_histories = sorted.length.times.collect{ |i| histories[sorted[i][1]] }
    
    # aggregate the values by processing the histories in the sort order
    a = Array.new
    f = Array.new
    p = Array.new
    a_sum = f_sum = p_sum = 0.0
    current_rep_id = sorted_histories[0].rep_id
    sorted_histories.each do |history|
      if history.rep_id == current_rep_id
        # still on current rep
        a_sum += history.amount_achieved
        f_sum += history.amount_forecast
        p_sum += history.amount_pipeline
      else
        # encountered a new rep; finish up the previous rep and start the new
        a << a_sum
        f << f_sum
        p << p_sum
        a_sum = history.amount_achieved
        f_sum = history.amount_forecast
        p_sum = history.amount_pipeline
        current_rep_id = history.rep_id
      end
    end
    
    # finish up the last rep and return the hash
    a << a_sum

app/helpers/analytics_helper.rb
module AnalyticsHelper
  
  # returns the total number of deals for the given array of summary objects
  def summary_total_num_deals(summaries)
    sum = 0
    summaries.each do |summary|
      sum += summary.num_deals
    end
    sum
  end
  
  # returns the total of the means for the given array of summary objects
  def summary_total_means(summaries)
    sum = 0.0
    summaries.each do |summary|
      sum += summary.mean
    end
    sum
  end
  
  # returns the total of the factored means for the given array of summary objects
  def summary_total_f_means(summaries)
    sum = 0.0
    summaries.each do |summary|
      sum += summary.f_mean
    end
    sum
  end
  
  # returns the total of the modes for the given array of summary objects
  def summary_total_modes(summaries)
    sum = 0.0
    summaries.each do |summary|
      sum += summary.mode
    end
    sum
  end

  # returns the total of the factored modes for the given array of summary objects
  def summary_total_f_modes(summaries)
    sum = 0.0
    summaries.each do |summary|
      sum += summary.f_mode
    end
    sum
  end
  
  # returns the total current forecast for the given array of 'source' objects
  # a source may be a region or a rep
  def source_total_forecasts(sources)
    sum = 0.0
    sources.each do |source|
      sum += source.current_forecast
    end
    sum
  end

  # returns the total current pipeline for the given array of 'source' objects
  # a source may be a region or a rep
  def source_total_pipelines(sources)
    sum = 0.0
    sources.each do |source|
      sum += source.current_pipeline
    end
    sum
  end  

  # returns the total current pipeline for the given array of 'source' objects
  # a source may be a region or a rep
  def source_total_open_deals(sources)
    sum = 0.0
    sources.each do |source|
      sum += source.open_deals
    end
    sum
  end
  
  # returns the total number of deals (open deals) for the given array of 'source' objects
  # a source may be a region or a rep
  def source_total_num_deals(sources)
    sum = 0
    sources.each do |source|
      sum += source.num_deals
    end
    sum
  end
  
  # returns the total number of pipeline deals for the given array of 'source' objects
  # a source may be a region or a rep
  def source_total_num_pipelines(sources)
    sum = 0
    sources.each do |source|
      sum += source.num_pipeline
    end
    sum
  end
  
  # returns the total number of forecast deals for the given array of 'source' objects
  # a source may be a region or a rep
  def source_total_num_forecasts(sources)
    sum = 0
    sources.each do |source|
      sum += source.num_forecast
    end
    sum
  end
end

app/views/analytics/chart_achieved_vs_x.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
  <br />
	<p id="notice_red"><%= flash[:notice] %>&nbsp;</p>
	<h3>Scope = <%= @scope %> <% if @theta != nil %>, theta = <%= @theta %>&deg;<% end %></h3>
	<% form_tag_url = url_for(:controller => 'analytics', :action => 'chart_achieved_vs_x', :avx_type => @avx_type) %>  
	<% form_tag form_tag_url do %>
	<p>	
	  <!-- make the filter_by radio button list, checking the button in @filter_by -->
		Filter by:
		<% ['show_all', 'show_region', 'show_rep'].each do |filter_avx_by| %>
		  &nbsp;<%= radio_button_tag 'filter_avx_by', filter_avx_by, @filter_avx_by == filter_avx_by %><%= filter_avx_by.humanize %>
		  <% if filter_avx_by == 'show_region' %>
        &nbsp;<%= collection_select :region_select, :id, @regions, :id, :name, :prompt => 'Select a region' %>  
      <% elsif filter_avx_by == 'show_rep' %>
  		  &nbsp;<%= collection_select :rep_select, :id, @reps, :id, :name, :prompt => 'Select a rep' %>
		  <% end %>
		<% end %>
    &nbsp;Aggregate histories? <%= check_box_tag :aggregate_histories, 1, @aggregate_histories_checked %>
  	
	</p>
	<p>
	  <%= submit_tag "Filter" %>
  	<%= link_to 'View analytics functions list', :controller => 'analytics', :action => 'index' %>
  <% end %>
	</p>
	<p></p>
</div>

<br /><br /><br />

<div id="chart">
  <%= image_tag @avx_vis %>
</div>

app/views/analytics/chart_likely_histo.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
  <br />
	<h3>
		Histogram (frequency distribution) of deal most likely values
	</h3>

	<p>
		<%= link_to 'View analytics functions list', :controller => 'analytics', :action => 'index' %> |
		<%= link_to 'Show deals', :controller => 'deals', :action => 'index' %> |
	</p>
</div>

<div id="chart">
  <%= image_tag @mlv_histo_vis %>
</div>

app/views/analytics/chart_pdf_cdf.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<h3>
		Chart of simulation sample distribution (<span style="color:#ff6633;">orange</span>) and 
		cumulative distribution (<span style="color:#3366ff;">blue</span>) <br />with 
		sample mean (<span style="color:#009900;">green</span>) and median (<span style="color:#990000;">red</span>) 
		<!-- deleteing most likely/mode - ambiguous and potentially misleading
		and most likely (<span style="color:#330066;">purple</span>) values
		-->
	</h3>

	<p>
		<%= link_to 'View analytics functions list', :controller => 'analytics', :action => 'index' %> |
		<%= link_to 'Show deals', :controller => 'deals', :action => 'index' %> |
	</p>
</div>

<div id="chart">
  <%= image_tag @pf_vis %>
</div>

app/views/analytics/chart_prob_histo.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
  <br />
	<h3>
		Histogram (frequency distribution) of deal win probabilities
	</h3>

	<p>
		<%= link_to 'View analytics functions list', :controller => 'analytics', :action => 'index' %> |
		<%= link_to 'Show deals', :controller => 'deals', :action => 'index' %> |
	</p>
</div>

<div id="chart">
  <%= image_tag @p_histo_vis %>
</div>

app/views/analytics/index.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<p> </p>

</div>

<div style="width:700px;">
  
<table>
	<tr><th class="list_table_heading" style="width:700px; text-align:left; padding-left:5px;">Select an Analytics function</th></tr>
</table>

<h4>Summaries</h4>
<p>
	<% summarize_deals_url = url_for(:controller => 'analytics', :action => 'summarize_deals') %>
	<%= link_to 'Summarize deals', summarize_deals_url %> &nbsp;&nbsp;|&nbsp; See a summary of details and basic statistics for the defined deals.                                                                
</p> 
<p>
	<% summarize_reps_url = url_for(:controller => 'analytics', :action => 'summarize_all_reps') %>
	<%= link_to 'Summarize deals by rep', summarize_reps_url %> &nbsp;&nbsp;|&nbsp; See a rep-by-rep summary of deals.                                                                
</p>
<p>
	<% summarize_regions_url = url_for(:controller => 'analytics', :action => 'summarize_all_regions') %>
	<%= link_to 'Summarize deals by region', summarize_regions_url %> &nbsp;&nbsp;|&nbsp; See a region-by-region summary deals.                                                                
</p>

<h4>Simulations</h4>
<p>
	<% simulate_parameters_url = url_for(:controller => 'analytics', :action => 'simulate_parameters') %>
	<%= link_to 'Simulate deals', simulate_parameters_url %> &nbsp;&nbsp;|&nbsp; See detailed outcome probabilities and 
	  statistics produced using a technique called 'monte carlo simulation' which is used to analyze
		scenarios where there is uncertainty about possible results.
</p>

<h4>Charts</strong></h4>
<p>
  <% chart_likely_histo_url = url_for(:controller => :analytics, :action => 'chart_likely_histo')%>
  <%= link_to 'Chart most likely values', chart_likely_histo_url %> &nbsp;&nbsp;|&nbsp; View a histogram
    showing the distribution of deal most likely values.
</p>
<p>
  <% chart_prob_histo_url = url_for(:controller => :analytics, :action => 'chart_prob_histo')%>
  <%= link_to 'Chart stages/win probabilities', chart_prob_histo_url %> &nbsp;&nbsp;|&nbsp; View a histogram
    showing the distribution of deal stages (win probabilities).
</p>
<p>
  <% chart_avx_url = url_for(:controller => :analytics, :action => 'chart_achieved_vs_x', :filter_avx_by => 'show_all', :aggregate_histories => '1', :avx_type => :forecast )%>
  <%= link_to 'Chart achieved results vs. forecast', chart_avx_url %> &nbsp;&nbsp;|&nbsp; View a plot of 
		achieved results vs. forecasts.
</p>
<p>
  <% chart_avx_url = url_for(:controller => :analytics, :action => 'chart_achieved_vs_x', :filter_avx_by => 'show_all', :aggregate_histories => '1', :avx_type => :pipeline )%>
  <%= link_to 'Chart achieved results vs. pipeline', chart_avx_url %> &nbsp;&nbsp;|&nbsp; View a plot of 
		achieved results vs. pipelines.
</p>
</div>

app/views/analytics/simulate_deals.html.erb
<div>
	<p>
		<%= link_to 'View analytics list', :controller => 'analytics', :action => 'index' %> |
		<%= link_to 'Show deals', :controller => 'deals', :action => 'index' %> |
	</p>
</div>

<!-- # write the table only if sim status is ok -->
<% if @sim.status == "ok" %>  

<table>
  <tr>
    <th class="analytics_table_header_name">Simulation results for <%= @sim.selected_count %> of <%= @deals.length %> deals</th>
    <th class="analytics_table_header_data">Simulated</th>
  </tr>

	<tr>
  	<td class="analytics_table_name">Expected (mean) total value</td>
  	<td class="analytics_table_data"><%=  number_to_currency @sim.mean %></td>
  	<td class="analytics_table_note_short">&nbsp;<%=h number_to_percentage 100 * @sim.mean / @sim.mean, :precision => 0 %></td>
  </tr>

	<tr>
  	<td class="analytics_table_name">Standard deviation (from mean)</td>
  	<td class="analytics_table_data"><%=  number_to_currency @sim.standard_deviation %></td>
  	<td class="analytics_table_note_short">&nbsp;<%=h number_to_percentage 100 * @sim.standard_deviation / @sim.mean, :precision => 0 %></td>
  </tr>

  <tr>
  	<td class="analytics_table_name">Minimum total value</td>
  	<td class="analytics_table_data"><%= number_to_currency @sim.min %></td>
  	<td class="analytics_table_note_short">&nbsp;<%=h number_to_percentage 100 * @sim.min / @sim.mean, :precision => 0 %></td>
  </tr>

	<tr>
  	<td class="analytics_table_name">Maximum total value</td>
  	<td class="analytics_table_data"><%= number_to_currency @sim.max %></td>
  	<td class="analytics_table_note_short">&nbsp;<%=h number_to_percentage 100 * @sim.max / @sim.mean, :precision => 0 %></td>
  </tr>

	<tr>
  	<td class="analytics_table_name">50% probability forecast (sample median)</td>
  	<td class="analytics_table_data"><%=  number_to_currency @sim.median %></td>
  	<td class="analytics_table_note_short">&nbsp;<%=h number_to_percentage 100 * @sim.median / @sim.mean, :precision => 0 %></td>
  </tr>
  
  <tr>
  	<td class="analytics_table_name">60% probability forecast</td>
  	<td class="analytics_table_data"><%= number_to_currency @sim.p_60 %></td>
  	<td class="analytics_table_note_short">&nbsp;<%=h number_to_percentage 100 * @sim.p_60 / @sim.mean, :precision => 0 %></td>
  </tr>
  
  <tr>
  	<td class="analytics_table_name">70% probability forecast</td>
  	<td class="analytics_table_data"><%= number_to_currency @sim.p_70 %></td>
  	<td class="analytics_table_note_short">&nbsp;<%=h number_to_percentage 100 * @sim.p_70 / @sim.mean, :precision => 0 %></td>
  </tr>
  
  <tr>
  	<td class="analytics_table_name">80% probability forecast</td>
  	<td class="analytics_table_data"><%= number_to_currency @sim.p_80 %></td>
  	<td class="analytics_table_note_short">&nbsp;<%=h number_to_percentage 100 * @sim.p_80 / @sim.mean, :precision => 0 %></td>
  </tr>
  
  <tr>
  	<td class="analytics_table_name">90% probability forecast</td>
  	<td class="analytics_table_data"><%= number_to_currency @sim.p_90 %></td>
  	<td class="analytics_table_note_short">&nbsp;<%=h number_to_percentage 100 * @sim.p_90 / @sim.mean, :precision => 0 %></td>
  </tr>
  
  <!-- spacer_flag makes sure the spacer row is only displayed once -->
  <% spacer_flag = false %>
  
  <% if @sim.p_le_target != nil %>
    <% if spacer_flag == false
      spacer_flag = true %>
      <tr class="row_spacer"><td> </td></tr>
    <% end %>
    <tr>
    	<td class="analytics_table_name">Probability >= target forecast</td>
    	<td class="analytics_table_data"><%= 1 - @sim.p_le_target %></td>
    </tr>    
  <% end %>
  
  <% if @sim.p_range != nil %>
    <% if spacer_flag == false
      spacer_flag = true %>
      <tr class="row_spacer"><td> </td></tr>
    <% end %>
    <tr>
    	<td class="analytics_table_name">Probability in min/max range</td>
    	<td class="analytics_table_data"><%= @sim.p_range %></td>
    </tr>    
  <% end %>
  
  <% if @sim.p_ge_min != nil %>
    <% if spacer_flag == false
      spacer_flag = true %>
      <tr class="row_spacer"><td> </td></tr>
    <% end %>
    <tr>
    	<td class="analytics_table_name">Probability >= min</td>
    	<td class="analytics_table_data"><%= @sim.p_ge_min %></td>
    </tr>    
  <% end %>
  
  <% if @sim.p_le_max != nil %>
    <% if spacer_flag == false
      spacer_flag = true %>
      <tr class="row_spacer"><td> </td></tr>
    <% end %>
    <tr>
    	<td class="analytics_table_name">Probability =< max</td>
    	<td class="analytics_table_data"><%= @sim.p_le_max %></td>
    </tr>    
  <% end %>
  
</table>

<p>
	<%= link_to 'Simulate again', :controller => 'analytics', :action => 'simulate_parameters' %>&nbsp;|
	<%= link_to 'View probability functions', :controller => 'analytics', :action => 'chart_pdf_cdf', :vis => @pf_vis %>
</p>

<% end %>