config/routes.rb
Dd3::Application.routes.draw do

  resources :site do
    collection do
      get 'index'
      get 'info'
      get 'signin'
      get 'privacy'
      get 'blog'
      get 'faq'
      get 'about'
    end
  end
  
  resources :deals do
   collection do
    post 'order_deals'
    get 'index_deals'
    get 'scenario'
    post 'create_new_scenario'
    get 'index_first_page'
    get 'index_last_page'
    get 'index_previous_page'
    get 'index_next_page'
    get 'delete_random_deals'
   end
  end  

  resources :reps do
    resources :deals
    get 'order_reps', :on => :collection
    get 'rank_reps', :on => :collection
  end
  
  resources :regions do
    resources :reps
    get 'order_regions', :on => :collection
  end
  
  resources :histories do
    resources :reps
  end
  
  resources :home
  
  resources :analytics do
    collection do
      get 'summarize_deals'
      get 'summarize_all_reps'
      get 'summarize_all_regions'
      get 'summarize_this_rep'
      get 'summarize_this_region'
      get 'simulate_parameters'
      get 'chart_pdf_cdf'
      get 'chart_likely_histo'
      get 'chart_prob_histo'
      get 'chart_achieved_vs_x'
      get 'chart_achieved_vs_forecast'
      get 'chart_achieved_vs_pipeline'
    end
  end
    
  resources :express do
    collection do
      post 'upload_file'
    end
  end
  
  resources :customers
  
  resources :scenarios
  
  resources :users
  resources :admin
  
  resources :sessions do
    collection do
      get 'signin_success'
      get 'signout_success'
    end
  end

  root :to => 'site#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/rep.rb
class Rep < ActiveRecord::Base
  belongs_to :region
  has_many :deals
  has_many :histories
  validates_presence_of :name, :allow_nil => false, :allow_blank => false, :message => "Must have a name"  
  validates_presence_of :region_id, :allow_nil => false, :allow_blank => false, :message => "Must select a region"  
  
  #
  # class methods
  #
  
  #require "regression"
  
  # returns the rep's current total open deals
  def open_deals
    sum = 0.0
    self.deals.each do |d|
      sum += d.most_likely_value
    end
    sum
  end

  # returns the rep's current total pipeline
  def current_pipeline
    sum = 0.0
    self.deals.each do |d|
      if d.is_pipeline then sum += d.most_likely_value end
    end
    sum
  end
  
  # returns the most likely value for all rep's deals with is_forecast flag set
  def current_forecast
    sum = 0.0
    self.deals.each do |d|
      if d.is_forecast then sum += d.most_likely_value end
    end
    sum
  end
  
  # returns the reps current forecast coverage
  def current_forecast_coverage
    self.current_pipeline / self.current_forecast
  end
  
  # returns the total number of deals currently open
  def num_deals
    sum = 0
    self.deals.each do |deal|
      if deal.stage_name != "Closed Won" && deal.stage_name != "Closed Lost"
        sum +=1
      end
    end
    sum
  end
  
  # returns the number of deals with is_pipeline flag set
  def num_pipeline
    sum = 0
    self.deals.each do |d| 
      if d.is_pipeline then sum += 1 end
    end
    sum
  end
  
  # returns the number of deals with is_forecast flag set
  def num_forecast
    sum = 0
    self.deals.each do |d| 
      if d.is_forecast then sum += 1 end
    end
    sum
  end
  
  # return the weighted average forecast accuracy (achieved / forecast) for rep's histories
  # the weighting factor is the amount forecast (terms cancel to give the ratio of sums)
  def forecast_accuracy
    sum_f = sum_a = 0.0
    self.histories.each do |h|
      sum_a += h.amount_achieved
      sum_f += h.amount_forecast
    end
    sum_f > 0.0 ? sum_a / sum_f : 0.0
  end
  
  # return the weighted average pipeline accuracy (achieved / pipeline) for rep's histories
  # the weighting factor is the amount pipeline (terms cancel to give the ratio of sums)
  def pipeline_accuracy
    sum_p = sum_a = 0.0
    self.histories.each do |h|
      sum_a += h.amount_achieved
      sum_p += h.amount_pipeline
    end
    sum_p > 0.0 ? sum_a / sum_p : 0.0
  end
  
  # return the weighted average forecast coverage (pipeline / forecast)
  # the weighting factor is the amount forecast and is implicit in the calc
  def forecast_coverage
    sum_f = self.sum_forecast_history
    sum_p = self.sum_pipeline_history
    sum_f > 0.0 ? sum_p / sum_f : 0.0    
  end
  
  # return the weighted average achieved coverage (pipeline / achieved)
  # the weighting factor is the amount forecast and is implicit in the calc 
  def achieved_coverage
    sum_a = self.sum_achieved_history
    sum_p = self.sum_pipeline_history
    sum_a > 0.0 ? sum_p / sum_a : 0.0    
  end
  
  # returns the rank value, i.e., the value used in the ranking calc
  # the rank value is the weighted average of the 'distance' of the rep's
  # historical forecast accuracy and the 'true' value of 1.0, and theta expressed in radians
  # weighting factor a is given in the calc and is entirely arbitrary
  def rank_value
    a = 0.8
    a * (1 - self.forecast_accuracy).abs + (1.0 - a) * self.amount_predicted_regression[:theta] * 3.14159 / 180.0
  end
  
  # returns a predicted value of the rep's amount achieved based on current forecast and pipeline values
  # uses a linear regression on the historical forecast, pipeline and achieved data
  # note: returns a hash combining the value and the theta (angle to 45-degree true forecast line)
  def amount_predicted_regression(mode)
    if self.histories.length == 0 then return Hash[:value => 0, :theta => 0] end
    if mode == :forecast # use only forecast values
      x = self.histories.collect { |h| [h.amount_forecast] }
    elsif mode == :pipeline # use only pipeline values
      x = self.histories.collect { |h| [h.amount_pipeline] }
    else # use both forecast and pipeline values
      x = self.histories.collect { |h| [h.amount_forecast, h.amount_pipeline] }
    end
    y = self.histories.collect { |h| h.amount_achieved }
    r = Regression.new
    r.lr(x, y, true) 
    if mode == :forecast
      Hash[:value => r.evaluate([self.current_forecast]), :theta => r.theta_degrees] 
    elsif mode == :pipeline
      Hash[:value => r.evaluate([self.current_pipeline]), :theta => r.theta_degrees] 
    else
      Hash[:value => r.evaluate([self.current_forecast, self.current_pipeline]), :theta => r.theta_degrees] 
    end
  end
  
  # returns the ratio of the regression current prediction to the current forecast
  def predicted_accuracy(mode)
    self.amount_predicted_regression(mode)[:value] / self.current_forecast
  end
  
  # this method simply uses the historical average
  def amount_predicted_average
    self.forecast_accuracy * self.current_forecast
  end
  
  #
  # methods to sum the rep's various history amounts
  #
  
  def sum_achieved_history
    sum = 0.0
    self.histories.each do |history|
      sum += history.amount_achieved
    end
    sum
  end
  
  def sum_forecast_history
    sum = 0.0
    self.histories.each do |history|
      sum += history.amount_forecast
    end
    sum
  end

  def sum_pipeline_history
    sum = 0.0
    self.histories.each do |history|
      sum += history.amount_pipeline
    end
    sum
  end
  
  
end

app/controllers/reps_controller.rb
# Copyright © by David M. Spenhoff. All rights reserved

include SharedMethods
require "simulation"			# simulates deals

class RepsController < ApplicationController
  
  before_filter :login_required
	
  # GET /reps
  def index
    @reps = Rep.all
    @order_by = "none"
    @page_title = "Reps"
  end
  
  # GET /reps/1
  def show
    @rep = Rep.find(params[:id])
    @sim = Simulation.new
    @sim.simulate(@rep.deals, 'mode', 'given', nil, 1.0, nil, nil, nil)
    @page_title = "Reps > Show"
  end

  # GET /reps/new
  def new
    @rep = Rep.new
    @regions = Region.all     # for the collection_select
    @page_title = "Reps > New"
  end

  # GET /reps/1/edit
  def edit
    @rep = Rep.find(params[:id])
    @regions = Region.all     # for the collection_select
    @page_title = "Reps > Edit"
  end

  # POST /reps
  def create
    @rep = Rep.new(params[:rep], :without_protection => true)
    if @rep.save
      flash[:notice] = 'Rep was successfully created.'
      redirect_to(@rep)
    else
      render :action => "new" 
    end
  end

  # PUT /reps/1
  def update
    @rep = Rep.find(params[:id])
    if @rep.update_attributes(params[:rep], :without_protection => true)
      flash[:notice] = 'Rep was successfully updated.'
      redirect_to(@rep) 
    else
      render :action => "edit" 
    end
  end

  # DELETE /reps/1
  def destroy
    # confirm that the rep is empty (no deals) before deleting
    @rep = Rep.find(params[:id])
    if @rep.deals == []   # if rep is empty it can be deleted
      @rep.destroy
      destroy_notice = "Region was successfully deleted"      
    else
      destroy_notice = "Region has assigned reps or deals and cannot be deleted"
    end
    flash[:notice] = destroy_notice
    redirect_to(reps_url)
  end
  
  #
  # methods to show the rep's associated deals and histories
  #

  # show the deals that belong to the given rep
  def show_associated_deals
    @order_by = "none"
    session[:order_by] = "id"
    show_rep_deals
  end
  
  # orders the deals according to the given parameters
  def order_rep_deals
    @order_by = params[:order_by]   # parameter returned to the view
    order_deals_by(@order_by)   # shared
    show_rep_deals
  end
  
  # gets and renders ordered rep deals with the deals/index view
  def show_rep_deals
    @rep = Rep.find(params[:id])
    @deals = @rep.deals.all(:order =>session[:order_by])
    flash.now[:notice] = @deals.length.to_s + " deals" 
    @page_title = "Rep > View deals (" + @rep.name + ")"
    @reps_controller = true
    render "deals/index"  # display using deals controller/formatting
  end
  
  def show_associated_histories
    @rep = Rep.find(params[:id])
    @histories = @rep.histories
    @page_title = "Reps > View history"
    #flash.now[:notice] = "Viewing history for rep " + @rep.name
  end
  
  # sorts the reps according to the order_by parameter
  # in deals, order_by is accomplished in the database call
  # here some of the sort fields are not database fields so
  # a different approach is needed:
  # - based on the order_by parameter sort a tracking array containing the appropriate value
  # - then apply the sort order to the @reps array according to the sorted tracking index
  def order_reps    
    reps = Rep.all
    @order_by = params[:order_by]
    
    # create a sorted tracking array according to the ordering parameter
    case @order_by 
    when "num_deals"
      sorted = reps.length.times.collect{ |i| [reps[i].num_deals, i]}.sort!
    when "num_forecast"
      sorted = reps.length.times.collect{ |i| [reps[i].num_forecast, i]}.sort!
    when "pipeline"
      sorted = reps.length.times.collect{ |i| [reps[i].current_pipeline, i]}.sort!
    when "forecast"
      sorted = reps.length.times.collect{ |i| [reps[i].current_forecast, i]}.sort!
    when "accuracy"
      sorted = reps.length.times.collect{ |i| [reps[i].forecast_accuracy, i]}.sort!
    when "rank"
      sorted = reps.length.times.collect{ |i| [reps[i].rank_value, i]}.sort!
    else
      # default (eg, order_by = none)
      sorted = reps.length.times.collect{ |i| [reps[i].id, i] }.sort!
    end      
        
    if @order_by != "none" && @order_by != "rank" then sorted.reverse! end
    
    # apply the sort order index to the reps array
    @reps = sorted.length.times.collect{ |i| reps[sorted[i][1]] }
    @page_title = "Reps"
    render :index
  end
  

  
end

app/helpers/reps_helper.rb
module RepsHelper
  
  # returns the total number of deals for the given collection of reps
  def total_rep_num_deals(reps)
    sum = 0
    reps.each do |rep|
      sum += rep.num_deals
    end
    sum  
  end
  
  # returns the total number of deals forecast for the given collection of reps
  def total_rep_num_deals_forecast(reps)
    sum = 0
    reps.each do |rep|
      sum += rep.num_forecast
    end
    sum
  end
  
  # returns the total of the current forecast for the given collection of reps
  def total_rep_forecast(reps)
    sum = 0.0
    reps.each do |rep|
      sum += rep.current_forecast
    end
    sum
  end
  
  # returns the total of the current pipeline for the given collection of reps
  def total_rep_pipeline(reps)
    sum = 0.0
    reps.each do |rep|
      sum += rep.current_pipeline
    end
    sum
  end
    
  # returns the average forecast average for the given collection of reps
  # note the return value needs to be multiplied by 100 to get a percentage
  def average_rep_forecast_accuracy(reps)
    sum = 0.0
    reps.each do |rep|
      sum += rep.forecast_accuracy
    end
    sum / reps.length
  end  
  
  # returns the average pipeline coverage for the given collection of reps
  # note the return value needs to be multiplied by 100 to get a percentage
  def average_rep_forecast_coverage(reps)
    sum = 0.0
    reps.each do |rep|
      sum += rep.forecast_coverage
    end
    sum / reps.length
  end
  
  # returns the total (aggregate) forecast coverage for the given collection of reps
  # note the return value needs to be multiplied by 100 to get a percentage
  def total_rep_forecast_coverage(reps)
    sum_f = sum_p = 0.0
    reps.each do |rep|
      sum_f += rep.amount_forecast
      sum_p += rep.amount_pipeline
    end
    sum_f > 0 ? sum_p / sum_f : 0.0
  end
  
  # returns the historical forecast coverage for the collection of reps, aggregated over the reps' histories
  # see caveats above
  def total_rep_forecast_coverage(reps)
    sum_f = sum_p = 0.0
    reps.each do |rep|
      rep.histories.each do |history|
        sum_f += history.amount_forecast
        sum_p += history.amount_pipeline
      end
    end
    sum_f > 0 ? sum_p / sum_f : 0.0
  end
  
  # returns the historical achieved coverage for the collection of reps, aggregated over the reps' histories
  # see caveats above
  def total_rep_achieved_coverage(reps)
    sum_a = sum_p = 0.0
    reps.each do |rep|
      rep.histories.each do |history|
        sum_a += history.amount_achieved
        sum_p += history.amount_pipeline
      end
    end
    sum_a > 0 ? sum_p / sum_a : 0.0
  end
  
  # returns the total forecast predicted for the given collection of reps
  # using the linear regression on the historical data
  def total_rep_predicted_regression(reps)
    sum = 0.0
    reps.each do |rep|
      sum += rep.amount_predicted_regression
    end
    sum
  end
  
  
  
  # returns the total forecast predicted for the given collection of reps
  # using the average achievement on the historical data
  def total_rep_predicted_average(reps)
    sum = 0.0
    reps.each do |rep|
      sum += rep.amount_predicted_average
    end
    sum
  end
    
end

app/views/reps/edit.html.erb
<!-- Copyright (c) by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<p>Editing rep</p>
	<p>	</p>
	<p>	</p>
</div>

<%= form_for(@rep) do |f| %>
  <%= f.error_messages %>
  
  <table>
    <tr>
      <td class = "view_table_name">Name</td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td class = "view_table_name">Region</td>
      <td><%= f.collection_select :region_id, @regions, :id, :name %> </td>
    </tr>
    <tr>
      <td class = "view_table_name">Current_forecast</td>
      <td><%= f.text_field :current_forecast %> </td>
    </tr>
  </table>
  
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<p>
  <%= link_to 'Show', @rep %> |
  <%= link_to 'Cancel', reps_path %>
</p>

app/views/reps/index.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<p id="notice_green"><%= flash[:notice] %>&nbsp;</p>
	<% form_tag_url = url_for(:controller => 'reps', :action => 'order_reps') %>  
	<%= form_tag form_tag_url do %>
	<p>	
	  <!-- make the order_by radio button list, checking the button in @order_by -->
		Order reps by:
		<% ['none', 'num_deals', 'num_forecast', 'pipeline', 'forecast', 'accuracy', 'rank'].each do |order_by| %>
		  &nbsp;&nbsp;<%= radio_button_tag 'order_by', order_by, @order_by == order_by %><%= order_by.humanize %>
		<% end %>
	</p>
	<p>
	  <%= submit_tag 'Order reps' %>
  	<%= link_to 'Create a new rep', new_rep_path %>
  <% end %>
	</p>
</div>

<div id="data">
  
<table>
  <tr class="list_table_heading">
    <th class="list_table_name">Name</th>
    <th class="list_table_name">Region</th>
		<th class="list_table_number">Num deals</th>
		<th class="list_table_number">Num forecast</th>
		<th class="list_table_amount">Pipeline</th>
    <th class="list_table_amount">Forecast</th>
		<th class="list_table_amount">Accuracy</th>
    <th class="list_table_action">Actions</th>
  </tr>

  <% @reps.each do |rep| %>
  <tr class="<%= cycle('list_table_row_even', 'list_table_row_odd') %>">
    <td class="list_table_name"><%=h rep.name %></td>
    <td class="list_table_name"><%=h rep.region.name %>
  	<td class="list_table_number"><%=h rep.num_deals %>
	  <td class="list_table_number"><%=h rep.num_forecast %>
		<td class="list_table_amount"><%=h number_to_currency rep.current_pipeline, :precision => 0 %></td>
    <td class="list_table_amount"><%=h number_to_currency rep.current_forecast, :precision => 0 %></td>
 		<td class="list_table_amount"><%=h number_to_percentage 100 * rep.forecast_accuracy, :precision => 0 %></td>
    <td class="region_action_links">
      <%= link_to 'Show rep', rep %>
      &nbsp;<%= link_to 'Show deals', { :controller => 'reps', :action => 'show_associated_deals', :id => rep.id } %>
      &nbsp;<%= link_to 'Show history', :controller => 'reps', :action => 'show_associated_histories', :id => rep.id %>
		</td>
  </tr>
  <% end %>
  <tr>
    <!-- skip the first 2 columns -->
    <td colspan="2"></td>
    <td class="list_table_footing_number"><%=h total_rep_num_deals(@reps) %></td>
    <td class="list_table_footing_number"><%=h total_rep_num_deals_forecast(@reps) %></td>
    <td class="list_table_footing_amount"><%=h number_to_currency total_rep_pipeline(@reps), :precision => 0 %></td>
    <td class="list_table_footing_amount"><%=h number_to_currency total_rep_forecast(@reps) , :precision => 0 %></td>
    <td class="list_table_footing_amount"><%=h number_to_percentage 100 * average_rep_forecast_accuracy(@reps), :precision => 0 %></td>
  </tr>
</table>

<% if @reps.length == 0 %>
	<p class="no_records">There are no rep records to display</p>	
<% end %>
</div>

app/views/reps/new.html.erb
<!-- Copyright (c) by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<p>New rep</p>
	<p>	</p>
	<p>	</p>
</div>

<%= form_for(@rep) do |f| %>
  <%= f.error_messages %>

  <table>
    <tr>
      <td class = "view_table_name">Name</td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td class = "view_table_name">Rep</td>
      <td><%= f.collection_select :region_id, @regions, :id, :name %> </td>
    </tr>
  </table>
  
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Cancel', reps_path %>

app/views/reps/show.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<h3>Showing rep: <%= @rep.name %></h3>
	<p>	</p>
	<p>	</p>
</div>

<p>
  <%= link_to 'Show history', :controller => 'reps', :action => 'show_associated_histories', :id => @rep.id %>
  | <%= link_to 'Show deals', :controller => 'reps', :action => 'show_associated_deals', :id => @rep.id %>
  | <%= link_to 'Show region', :controller => 'regions', :action => 'show', :id => @rep.region.id %>
  | <%= link_to 'Edit', edit_rep_path(@rep) %>
  | <%= link_to 'Delete', @rep, :confirm => 'Are you sure?', :method => :delete %>
</p>

<table>
  <tr>
    <td class="view_table_name">Name</td>
    <td class="view_table_data"><%=h @rep.name %></td>
  </tr>
  <tr>
    <td class="view_table_name">Region</td>
    <td class="view_table_data"><%=h @rep.region.name %></td>
  </tr>
  <tr>
    <td class="view_table_name">Deals open</td>
    <td class="view_table_data"><%=h @rep.num_deals %></td>
  </tr>

  <!-- summarize the pipeline -->
  <tr>
    <td class="view_table_name">Pipeline</td>
    <td class="view_table_data_medium"><%=h number_to_currency @rep.current_pipeline, :precision => 0 %></td>
    <td class="view_table_name">Deals in pipeline</td>
    <td class="view_table_data_short"><%=h @rep.num_pipeline %></td>
    <td class="view_table_name">Historical coverage</td>
    <td class="view_table_data_short"><%=h number_to_percentage 100 * @rep.forecast_coverage, :precision => 0 %></td>
  </tr>

  <!-- summarize the forecast -->
  <tr>
    <td class="view_table_name">Forecast</td>
    <td class="view_table_data_medium"><%=h number_to_currency @rep.current_forecast, :precision => 0 %></td>
    <td class="view_table_name">Deals in forecast</td>
    <td class="view_table_data_short"><%=h @rep.num_forecast %></td>
    <td class="view_table_name">Historical accuracy</td>
    <td class="view_table_data_short"><%=h number_to_percentage 100 * @rep.forecast_accuracy, :precision => 0 %></td>
  </tr>

  <!-- current forecast coverage -->
  <tr>
    <td class="view_table_name">Coverage </td>
    <td class="view_table_data_medium"><%=h number_to_percentage 100 * @rep.current_forecast_coverage, :precision => 0 %></td>
  </tr>
  
  <% if @rep.num_deals != 0 then %>
  <!-- exclude the rest of the summary if the rep has no deals -->
  
  <% if @rep.histories.length != 0 %>
  <!-- skip the predictions if rep has no histories -->
  
  <!-- the predictions -->
  <tr>
    <td class="view_table_name">Theta</td>
    <td class="view_table_data_medium"><%= @rep.amount_predicted_regression(:forecast_and_pipeline)[:theta].round %>&deg;</td>
  </tr>
  <tr>
    <td class="view_table_name">Predicted - regression </td>
    <td class="view_table_data_medium"><%=h number_to_currency @rep.amount_predicted_regression(:forecast_and_pipeline)[:value], :precision => 0 %></td>
  </tr>
  <tr>
    <td class="view_table_name">Predicted - accuracy</td>
    <td class="view_table_data_medium"><%=h number_to_currency @rep.amount_predicted_average, :precision => 0 %></td>
  </tr>
  <% end %>
  
  <!-- the simulation -->
  <tr>
    <td class="view_table_name">Simulated - 90%</td>
    <td class="view_table_data_medium"><%=h number_to_currency @sim.p_90, :precision => 0 %></td>
  </tr> 
  
  <% end %> 
  
</table>

<p>
  <%= link_to 'Back', reps_path %>
  | <%= link_to 'Create new rep', new_rep_path %>
</p>

app/views/reps/show_associated_histories.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<h3>Showing rep history for <%= @rep.name %></h3>

	<p>
	  <%= link_to 'Show rep ', :controller => 'reps', :action => 'show', :id => @rep.id %>
	  | <%= link_to 'Chart history', :controller => 'analytics', :action => 'chart_achieved_vs_forecast', 
	          :filter_avf_by => 'show_rep', :rep_select => {:id => @rep.id} %>
	  | <%= link_to 'Show deals for this rep ', :controller => 'reps', :action => 'show_associated_deals', :id => @rep.id %>
  </p>

</div>

<table>
	<tr class="list_table_heading">
		<th class="list_table_date">Date</th>
		<th class="list_table_amount">Actual amount</th>
		<th class="list_table_amount">Forecast amount</th>
		<th class="list_table_amount">Pipeline amount</th>
		<th class="list_table_amount">Forecast accuracy</th>
		<th class="list_table_amount">Pipeline coverage</th>
	</tr>
	<% @histories.each do |history| %>
	<tr class="<%= cycle('list_table_row_even', 'list_table_row_odd') %>">
		<td class="list_table_date"><%=h history.date.strftime('%d %b %Y') %></td>
		<td class="list_table_amount"><%=h number_to_currency history.amount_achieved, :precision => 0 %></td>
		<td class="list_table_amount"><%=h number_to_currency history.amount_forecast, :precision => 0 %></td>
		<td class="list_table_amount"><%=h number_to_currency history.amount_pipeline, :precision => 0 %></td>
		<td class="list_table_amount"><%=h number_to_percentage 100 * history.forecast_accuracy, :precision => 0 %></td>
		<td class="list_table_amount"><%=h number_to_percentage 100 * history.forecast_coverage, :precision => 0 %></td>
	</tr>
	<% end %>
  <tr>
    <!-- skip the first 1 columns -->
    <td colspan="1"></td>
    <td class="list_table_footing_amount"><%=h number_to_currency @rep.sum_achieved_history, :precision => 0 %></td>
    <td class="list_table_footing_amount"><%=h number_to_currency @rep.sum_forecast_history, :precision => 0 %></td>
    <td class="list_table_footing_amount"><%=h number_to_currency @rep.sum_pipeline_history, :precision => 0 %></td>
    <td class="list_table_footing_amount"><%=h number_to_percentage 100 * @rep.forecast_accuracy, :precision => 0 %></td>
    <td class="list_table_footing_amount"><%=h number_to_percentage 100 * @rep.forecast_coverage, :precision => 0 %></td>
  </tr>
</table>

<p>
  <%= link_to 'Back', reps_path %>
</p>