config/routes.rb
Dd3::Application.routes.draw do

  resources :site do
    collection do
      get 'index'
      get 'info'
      get 'signin'
      get 'privacy'
      get 'blog'
      get 'faq'
      get 'about'
    end
  end
  
  resources :deals do
   collection do
    post 'order_deals'
    get 'index_deals'
    get 'scenario'
    post 'create_new_scenario'
    get 'index_first_page'
    get 'index_last_page'
    get 'index_previous_page'
    get 'index_next_page'
    get 'delete_random_deals'
   end
  end  

  resources :reps do
    resources :deals
    get 'order_reps', :on => :collection
    get 'rank_reps', :on => :collection
  end
  
  resources :regions do
    resources :reps
    get 'order_regions', :on => :collection
  end
  
  resources :histories do
    resources :reps
  end
  
  resources :home
  
  resources :analytics do
    collection do
      get 'summarize_deals'
      get 'summarize_all_reps'
      get 'summarize_all_regions'
      get 'summarize_this_rep'
      get 'summarize_this_region'
      get 'simulate_parameters'
      get 'chart_pdf_cdf'
      get 'chart_likely_histo'
      get 'chart_prob_histo'
      get 'chart_achieved_vs_x'
      get 'chart_achieved_vs_forecast'
      get 'chart_achieved_vs_pipeline'
    end
  end
    
  resources :express do
    collection do
      post 'upload_file'
    end
  end
  
  resources :customers
  
  resources :scenarios
  
  resources :users
  resources :admin
  
  resources :sessions do
    collection do
      get 'signin_success'
      get 'signout_success'
    end
  end

  root :to => 'site#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :rep
  validates_presence_of :rep_id, :allow_nil => false, :allow_blank => false, :message => "Must select a rep"
  validates_presence_of :stage_name, :allow_nil => false, :allow_blank => false, :message => "Must select a stage"
  validates_presence_of :name, :allow_nil => false, :allow_blank => false, :message => "Must have a description"
  validates_presence_of :most_likely_value, :allow_nil => false, :allow_blank => false, :message => "Must have a most likely value"
  validates_numericality_of :most_likely_value, :message => "Most likely value must be a number"
  
  def deal_is_pipeline
    (self.probability >= 0.5 && self.probability < 1.0)
  end
  
  def deal_is_forecast
    (self.probability >= 0.75 && self.probability < 1.0)
  end
  
  #
  # rules used for deal creation/update
  #
  
  def apply_rules
    self.deal_probability_rule
    self.nil_value_rule
    self.forecast_pipeline_rule
  end
  
  def deal_probability_rule
    if self.stage_name != nil then self.probability = sfdc_stage_probability(self.stage_name) end
  end
  
  def nil_value_rule
    if self.most_likely_value != nil
      if self.minimum_value == nil then self.minimum_value = self.most_likely_value end
      if self.maximum_value == nil then self.maximum_value = self.most_likely_value end
    end
  end
  
  def forecast_pipeline_rule
    self.is_forecast = self.deal_is_forecast
    self.is_pipeline = self.deal_is_pipeline || self.is_forecast
  end
  
  
end

app/controllers/deals_controller.rb
# Copyright © by David M. Spenhoff. All rights reserved

include SharedMethods

class DealsController < ApplicationController
  
  before_filter :login_required
  
  # class constants to control the paged display of deals 
  @@page_size = 10 
  @@page_num = 0
  @@total_pages = 0 
  
  # GET /deals
  # GET /deals.xml
  def index
    session[:order_by] = "id"
    @order_by = session[:order_by_checked] = "none"
    session[:page_offset] = 0
    @deals = get_deals(session[:order_by], @@page_size, session[:page_offset])
    @page_title = "Deals"
  end
  
  #def index_deals
    # what is the purpose of this method? seems like nothing
  #end

  # GET /deals/1
  # GET /deals/1.xml
  def show
    @deal = Deal.find(params[:id])
    @page_title = "Deals > Show"
  end

  # GET /deals/new
  # GET /deals/new.xml
  def new
    @deal = Deal.new
    @reps = Rep.all
    @stages = sfdc_stages.collect{ |s| [sfdc_long_stage_name(s[:stage]), s[:stage].to_s] }
    @page_title = "Deals > New"
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
    @reps = Rep.all
    @stages = sfdc_stages.collect{ |s| [sfdc_long_stage_name(s[:stage]), s[:stage].to_s] }
    #@stages.unshift()
    @page_title = "Deals > Edit"
  end

  # POST /deals
  # POST /deals.xml
  def create
    @deal = Deal.new(params[:deal], :without_protection => true)
    @deal.apply_rules
    if @deal.save
      flash[:notice] = 'Deal was successfully created.'
      redirect_to(@deal)
    else
      @reps = Rep.all
      @stages = sfdc_stages.collect{ |s| [s[:stage].to_s, s[:stage].to_s] }
      @page_title = "Deals > New"
      render :action => "new" 
    end
  end

  # PUT /deals/1
  # PUT /deals/1.xml
  def update
    @deal = Deal.find(params[:id])
    if @deal.update_attributes(params[:deal], :without_protection => true)
      @deal.apply_rules
      if @deal.save
        flash[:notice] = 'Deal was successfully updated.'
        redirect_to(@deal)
      end
    else
      render :action => 'edit'
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.xml
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy
    redirect_to(deals_url)
  end 
  
  def scenario
    @page_title = "Deals > New scenario"
  end 
  
  def create_new_scenario
    # generate a new scenario of regions, reps, deals and histories based on params[]  
    # note the new scenario process (create) will first wipe out the existing scenario data 
    num_regions = params[:num_regions].to_i 
    num_reps = params[:num_reps].to_i
    num_deals = params[:num_deals].to_i
    num_histories = params[:num_histories].to_i
    over_achieve = params[:over_achieve].to_f
    under_achieve = params[:under_achieve].to_f
    new_scenario = Scenario.new
    if params[:deep_deals] == nil
      new_scenario.create(num_regions, num_reps, num_deals, num_histories, over_achieve, under_achieve)
    else
      new_scenario.create_deep(num_histories + 1, num_regions, num_reps, num_deals, num_histories, over_achieve, under_achieve)
    end
    #show the deals
    redirect_to(deals_url)
  end
  
  
  #
  # the following methods control the paging of the index display (deals listing)
  #
  
  # display the first page of deals
  def index_first_page
    session[:page_offset] = 0
    @deals = get_deals(session[:order_by], @@page_size, session[:page_offset])
    @order_by = session[:order_by_checked]
    @page_title = "Deals"
    render :index
  end
  
  # display the last page of deals
  def index_last_page
    session[:page_offset] = Deal.count - @@page_size
    if session[:page_offset] < 0 then session[:page_offset] = 0 end
    @deals = get_deals(session[:order_by], @@page_size, session[:page_offset])
    @order_by = session[:order_by_checked]
    @page_title = "Deals"
    render :index
  end
  
  # display the previous page of deals
  def index_previous_page
    session[:page_offset] = session[:page_offset] - @@page_size
    if session[:page_offset] < 0 then session[:page_offset] = 0 end
    @deals = get_deals(session[:order_by], @@page_size, session[:page_offset])
    @order_by = session[:order_by_checked]
    @page_title = "Deals"
    render :index
  end
  
  # display the first page of deals
  def index_next_page
    session[:page_offset] = session[:page_offset] + @@page_size
    if session[:page_offset] >= Deal.count then session[:page_offset] = Deal.count - @@page_size end
    @deals = get_deals(session[:order_by], @@page_size, session[:page_offset])
    @order_by = session[:order_by_checked]
    @page_title = "Deals"
    render :index
  end

  # loads deals in given order and with given offset (paging)
  def get_deals(order_by, limit, offset)
    #debugger
    flash.now[:notice] = Deal.count.to_s + " total deals"   
    @total_pages = (Deal.count.to_f / limit).ceil.to_i
    @page_num = (offset.to_f / limit).ceil.to_i + 1
    @deals_controller = true
    # old - Deal.all(:all, :order => order_by, :limit => limit, :offset => offset )
    Deal.all(:order => order_by, :limit => limit, :offset => offset )
  end
  
  #
  # the following method controls the display ordering of deals
  #
  
  def order_deals
    # the order_by filter
    @order_by = session[:order_by_checked] = params[:order_by]    # used in the view
    order_deals_by(@order_by)   # shared
    
    # page sizing
    session[:page_offset] = 0
    @deals = get_deals(session[:order_by], @@page_size, session[:page_offset])
    @page_title = "Deals"  
    render :index
  end
  
end

app/helpers/deals_helper.rb
module DealsHelper
  
  # returns the toals of the likely values for the given array of deals
  def total_deals_likely_value(deals)
    sum = 0.0
    deals.each do |deal|
      sum += deal.most_likely_value
    end
    sum
  end
end

app/views/deals/edit.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<p> </p>
	<p>	</p>
	<p>	</p>
</div>

<%= form_for(@deal) do |f| %>
  <%= f.error_messages %>
  
  <table>
<!--
  <p>
    <%= f.label :customer_id %><br />
    <%= f.text_field :customer_id %>
  </p>
-->
    <tr>
      <td class = "view_table_name">Description</td>
      <td><%= f.text_field :name %></td>
    </tr> 
    <tr>
      <td class = "view_table_name">Rep</td>
      <td><%= f.collection_select :rep_id, @reps, :id, :name %></td>
    </tr>
    <tr>
      <td class="view_table_name">Stage</td>
      <td><%= f.select :stage_name, @stages %></td>
    </tr>
    <tr>
      <td class = "view_table_name">Forecast?</td>
      <td><%= f.select :is_forecast, [['Yes', true], ['No', false]] %></td>
    </tr>
    <tr>
      <td class = "view_table_name">Pipeline?</td>
      <td><%= f.select :is_pipeline, [['Yes', true], ['No', false]] %></td>
    </tr>      
    <tr>
      <td class = "view_table_name">Minimum value</td>
      <td><%= f.text_field :minimum_value %></td>
    </tr>  
    <tr>
      <td class = "view_table_name">Most likely value</td>
      <td><%= f.text_field :most_likely_value %></td>
    </tr>  
    <tr>
      <td class = "view_table_name">Maximum value</td>
      <td><%= f.text_field :maximum_value %></td>
    </tr>  
    <tr>
      <td class = "view_table_name">Open date</td>
      <td><%= f.date_select :open_date %></td>
    </tr>  
    <tr>
      <td class = "view_table_name">Expected close date</td>
      <td><%= f.date_select :expected_close_date %></td>
    </tr>  
    <tr>
      <td class = "view_table_name">Actual close date</td>
      <td><%= f.date_select :actual_close_date %></td>
    </tr>
  </table>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Cancel', deals_path %>

app/views/deals/index.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<!-- the parameters to control the deals display -->
	<!-- note the return action (form_tag_url) is different for the deals and reps controller -->
	<% 
	  if @reps_controller
	    form_tag_url = url_for(:controller => 'reps', :action => 'order_rep_deals', :id => @rep.id)
	  elsif @regions_controller
	    form_tag_url = url_for(:controller => 'regions', :action => 'order_region_deals', :id => @region.id)
	  else
	    # else must be the deals controller
	    form_tag_url = url_for(:controller => 'deals', :action => 'order_deals')
	  end
	%>  
	<%= form_tag form_tag_url do %>
	<p>	
	  <!-- make the order_by radio button list, checking the button in @order_by -->
		Order deals by:
		<% ['none', 'stage', 'most_likely_value', 'is_pipeline'].each do |order_by| %>
		  &nbsp;&nbsp;<%= radio_button_tag 'order_by', order_by, @order_by == order_by %>&nbsp;<%= order_by.humanize %>
		<% end %>
	</p>
	<p>
	  <%= submit_tag "Order Deals" %>
   	<%= link_to 'New deal', :controller => 'deals', :action => 'new' %> 
   	<% if @deals_controller %> <!-- only show scenario control when controller source is deals -->
    | <%= link_to 'Generate new scenario', :controller => 'deals', :action => 'scenario' %> 
    <% end %>
	</p>
	<% end %>
</div>

<!-- show the table only if deals is defined -->
<% if !defined?(@deals).nil? %>
<table>
  <tr class="list_table_heading">
    <th class="list_table_name">Description</th>
    <th class="list_table_rep">Rep</th>
    <th class="list_table_region">Region</th>
    <th class="list_table_stage">Stage</th>
    <th class="list_table_amount">Likely value</th>
    <th class="list_table_amount">Pipeline?</th>
    <th class="list_table_date">Open date</th>
    <th class="list_table_date">Close date</th>
    <th class="list_table_action">Actions</th>
  </tr>

<% @deals.each do |deal| %>
  <tr class="<%= cycle('list_table_row_even', 'list_table_row_odd') %>">
    <td class="list_table_name"><%=h deal.name %></th>
    <td class="list_table_rep"><%=h deal.rep.name %></th>
    <td class="list_table_region"><%=h deal.rep.region.name %></th>
    <td class="list_table_stage"><%=h sfdc_short_stage_name(deal.stage_name) %></td>
    <td class="list_table_amount"><%=h number_to_currency deal.most_likely_value %></td>
    <td class="list_table_amount"><%= deal.is_pipeline ? 'Yes' : '' %>
    <td class="list_table_date"><%=h deal.open_date.strftime('%d %b %Y') %></td>
    <td class="list_table_date"><%=h deal.actual_close_date.strftime('%d %b %Y') %></td>
    <td class="action_links">
		  <%= link_to 'Show deal', deal %>
	  </td>
  </tr>
<% end %>
<% if !@deals_controller %>
  <tr>
    <!-- skip the first 4 columns -->
    <td colspan="4"></td>
    <td class="list_table_footing_amount"><%=h number_to_currency total_deals_likely_value(@deals) %></td>
    <% if @reps_controller %><td class="list_table_footing_amount"><%=h number_to_currency @rep.current_forecast %></td><% end %>
    <% if @regions_controller %><td class="list_table_footing_amount"><%=h number_to_currency @region.current_forecast %></td><% end %>
  </tr> 
<% end %>
</table>

<br />

<!-- only display the page nav if controller source is deals -->
<% if @deals_controller %>
  <p>
  <%= link_to "First page", :controller => 'deals', :action => 'index_first_page' %> |
  <%= link_to "Previous page", :controller => 'deals', :action => 'index_previous_page' %> |
  <%= link_to "Next page", :controller => 'deals', :action => 'index_next_page' %> |
  <%= link_to "Last page", :controller => 'deals', :action => 'index_last_page' %>
  &nbsp;&nbsp; (Showing page <%= @page_num %> of <%= @total_pages %> total pages)
  </p>
<% end %>

<% end %>

app/views/deals/index_deals.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<p id="notice_green"><%= flash[:notice] %>&nbsp;</p>
	<!-- the parameters to control the deals display -->
	<% form_tag url_for(:controller => 'deals', :action => 'order_deals') do %>
	<p>
		Order deals by:<%= radio_button_tag :order_by, 'none', params[:order_by], :checked => true %>None
		    &nbsp;<%= radio_button_tag :order_by, 'prob', params[:order_by], :checked => false %>Prob
        &nbsp;<%= radio_button_tag :order_by, 'min', params[:order_by], :checked => false %>Min value
				&nbsp;<%= radio_button_tag :order_by, 'max', params[:order_by], :checked => false %>Max value
				&nbsp;<%= radio_button_tag :order_by, 'mode', params[:order_by], :checked => false %>Likely value
	</p>

  <p>
		<%= submit_tag "Order Deals" %>
   	<%= link_to 'New deal', :controller => 'deals', :action => 'order_deals' %> | 
    <%= link_to 'Generate random deals', :controller => 'deals', :action => 'random' %> |
    <%= link_to 'Delete random deals', :controller => 'deals', :action => 'delete_random_deals' %>
	<% end %>

</div>

<!-- show the table only if deals is defined -->
<% if !defined?(@deals).nil? %>

<table>
  <tr class="list_table_heading">
    <th class="list_table_name">Description</th>
    <th class="list_table_probability">Prob</th>
    <th class="list_table_amount">Min value</th>
    <th class="list_table_amount">Likely value</th>
    <th class="list_table_amount">Max value</th>
    <th class="list_table_date">Open date</th>
    <th class="list_table_date">Close date</th>
    <th class="list_table_date">Actual date</th>
    <th class="list_table_action">Actions</th>
  </tr>

<% @deals.each do |deal| %>
  <tr class="<%= cycle('list_table_row_even', 'list_table_row_odd') %>">
    <td class="list_table_name"><%=h deal.name %></th>
    <td class="list_table_probability"><%=h '%.2f' % deal.probability %></td>
    <td class="list_table_amount"><%=h number_to_currency deal.minimum_value %></td>
    <td class="list_table_amount"><%=h number_to_currency deal.most_likely_value %></td>
    <td class="list_table_amount"><%=h number_to_currency deal.maximum_value %></td>
    <td class="list_table_date"><%=h deal.open_date.strftime('%d %b %Y') %></td>
    <td class="list_table_date"><%=h deal.expected_close_date.strftime('%d %b %Y') %></td>
    <td class="list_table_date"><%=h deal.actual_close_date.strftime('%d %b %Y') %></td>
    <td class="action_links">
		  <%= link_to 'Show', deal %>
    	<%= link_to 'Edit', edit_deal_path(deal) %>
    	<%= link_to 'Destroy', deal, :confirm => 'Are you sure?', :method => :delete %>
	  </td>
  </tr>
<% end %>
</table>

<br />
<p>
<%= link_to "First page", :controller => 'deals', :action => 'index_first_page' %> |
<%= link_to "Previous page", :controller => 'deals', :action => 'index_previous_page' %> |
<%= link_to "Next page", :controller => 'deals', :action => 'index_next_page' %> |
<%= link_to "Last page", :controller => 'deals', :action => 'index_last_page' %>
&nbsp;&nbsp; (Showing page <%= @page_num %> of <%= @total_pages %> total pages)
</p>

<% end %>

app/views/deals/new.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<p>Create a new deal</p>
	<p>	</p>
	<p>	</p>
</div>

<%= form_for(@deal) do |f| %>

<div id="data"> 
  <p class="error"><%= error_messages_for 'deal' %></p>
  <table>
<!--
  <p>
    <%= f.label :customer_id %><br />
    <%= f.text_field :customer_id %>
  </p>
-->
    <tr>
      <td class="view_table_name">Description</td>
      <td><%= f.text_field :name %></td>
    </tr>  
    <tr>
      <td class = "view_table_name">Rep</td>
      <td><%= f.collection_select :rep_id, @reps, :id, :name, :include_blank => true %> 
    </tr>
    <tr>
      <td class="view_table_name">Stage</td>
      <td><%= f.select :stage_name, @stages, :include_blank => true %></td>
    </tr>  
    <tr>
      <td class = "view_table_name">Forecast?</td>
      <td><%= f.select :is_forecast, [['No', false], ['Yes', true]] %></td>
    </tr>
    <tr>
      <td class = "view_table_name">Pipeline?</td>
      <td><%= f.select :is_pipeline, [['No', false], ['Yes', true]] %></td>
    </tr>
    <tr>
      <td class="view_table_name">Minimum value</td>
      <td><%= f.text_field :minimum_value %></td>
    </tr>  
    <tr>
      <td class="view_table_name">Most likely value</td>
      <td><%= f.text_field :most_likely_value %></td>
    </tr>  
    <tr>
      <td class="view_table_name">Maximum value</td>
      <td><%= f.text_field :maximum_value %></td>
    </tr>  
    <tr>
      <td class="view_table_name">Open date</td>
      <td><%= f.date_select :open_date %></td>
    </tr>  
    <tr>
      <td class="view_table_name">Expected close date</td>
      <td><%= f.date_select :expected_close_date %></td>
    </tr>  
    <tr>
      <td class="view_table_name">Actual close date</td>
      <td><%= f.date_select :actual_close_date %></td>
    </tr>
  </table>
    
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Cancel', deals_path %>

</div>

app/views/deals/scenario.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<p><span style="font-weight: bold;">New scenario generator</span></p>
	
	<%= form_tag url_for(:controller => 'deals', :action => 'create_new_scenario') do %>
    <p>Number of deals? <%= text_field_tag :num_deals, params[:num_deals], :size => 8 %></p>
	  <p>Number of regions? <%= text_field_tag :num_regions, params[:num_regions], :size => 8 %></p>
    <p>Number of reps? <%= text_field_tag :num_reps, params[:num_reps], :size => 8 %></p>
    <p>Number of histories per rep? <%= text_field_tag :num_histories, params[:num_histories], :size => 8 %></p>
    <p>Over achieving reps (%)? <%= text_field_tag :over_achieve, params[:over_achieve], :size => 8 %></p>
    <p>Under achieving reps (%)? <%= text_field_tag :under_achieve, params[:under_achieve], :size => 8 %></p>
    <p>Deep deals? <%= check_box_tag :deep_deals, "yes" %>
	  <p>
		  <%= submit_tag "Create Scenario" %>
		  <%= link_to 'Cancel', deals_path %> 
		</p>
	<% end %>
	<p>	</p>
</div>
<div>
	<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
<div>

app/views/deals/show.html.erb
<!-- Copyright © by David M. Spenhoff. All rights reserved -->

<div id="selector">
	<p id="notice_green"><%= flash[:notice] %>&nbsp;</p>
	<p>	</p>
	<p>	</p>
</div>

<p>
  <%= link_to 'Show rep', :controller => 'reps', :action => 'show', :id => @deal.rep.id %>
  | <%= link_to 'Show region', :controller => 'regions', :action => 'show', :id => @deal.rep.region.id %>
  | <%= link_to 'Edit', edit_deal_path(@deal) %>
  | <%= link_to 'Delete', @deal, :confirm => 'Are you sure?', :method => :delete %>
</p>

<table>
  <tr>
    <td class="view_table_name">Description</td>
    <td class="view_table_data"><%=h @deal.name %></td>
  </tr>
  <tr>
    <td class="view_table_name">Rep</td>
    <td class="view_table_data"><%=h @deal.rep.name %></td>
  </tr>
  <tr>
    <td class="view_table_name">Region</td>
    <td class="view_table_data"><%=h @deal.rep.region.name %></td>
  </tr>
  <tr>
    <td class="view_table_name">Stage</td>
    <td class="view_table_data"><%=h @deal.stage_name %></td>
  </tr>  <tr>
    <td class="view_table_name">Probability</td>
    <td class="view_table_data"><%=h '%.2f' % @deal.probability %></td>
  </tr>
  <tr>
    <td class="view_table_name">Forecast?</td>
    <td class="view_table_data"><%=h @deal.is_forecast ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
    <td class="view_table_name">Pipeline?</td>
    <td class="view_table_data"><%=h @deal.is_pipeline ? 'Yes' : 'No' %></td>
  </tr>
  <tr>
    <td class="view_table_name">Minimum value</td>
    <td class="view_table_data"><%=h number_to_currency @deal.minimum_value %></td>
  </tr>

  <tr>
    <td class="view_table_name">Most likely value</td>
    <td class="view_table_data"><%=h number_to_currency @deal.most_likely_value %></td>
  </tr>

  <tr>
    <td class="view_table_name">Maximum value</td>
    <td class="view_table_data"><%=h number_to_currency @deal.maximum_value %></td>
  </tr>

  <tr>
    <td class="view_table_name">Open date</td>
    <td class="view_table_data"><%=h @deal.open_date.strftime('%d %b %Y') %></td>
  </tr>

  <tr>
    <td class="view_table_name">Expected close date</td>
    <td class="view_table_data"><%=h @deal.expected_close_date.strftime('%d %b %Y') %></td>
  </tr>

  <tr>
    <td class="view_table_name">Actual close date</td>
    <td class="view_table_data"><%=h @deal.actual_close_date.strftime('%d %b %Y') %></td>
  </tr>
</table>

<p>
<%= link_to 'Back', deals_path %>
  | <%= link_to 'New deal', new_deal_path %>
</p>