config/routes.rb
Dd3::Application.routes.draw do

  resources :site do
    collection do
      get 'index'
      get 'info'
      get 'signin'
      get 'privacy'
      get 'blog'
      get 'faq'
      get 'about'
    end
  end
  
  resources :deals do
   collection do
    post 'order_deals'
    get 'index_deals'
    get 'scenario'
    post 'create_new_scenario'
    get 'index_first_page'
    get 'index_last_page'
    get 'index_previous_page'
    get 'index_next_page'
    get 'delete_random_deals'
   end
  end  

  resources :reps do
    resources :deals
    get 'order_reps', :on => :collection
    get 'rank_reps', :on => :collection
  end
  
  resources :regions do
    resources :reps
    get 'order_regions', :on => :collection
  end
  
  resources :histories do
    resources :reps
  end
  
  resources :home
  
  resources :analytics do
    collection do
      get 'summarize_deals'
      get 'summarize_all_reps'
      get 'summarize_all_regions'
      get 'summarize_this_rep'
      get 'summarize_this_region'
      get 'simulate_parameters'
      get 'chart_pdf_cdf'
      get 'chart_likely_histo'
      get 'chart_prob_histo'
      get 'chart_achieved_vs_x'
      get 'chart_achieved_vs_forecast'
      get 'chart_achieved_vs_pipeline'
    end
  end
    
  resources :express do
    collection do
      post 'upload_file'
    end
  end
  
  resources :customers
  
  resources :scenarios
  
  resources :users
  resources :admin
  
  resources :sessions do
    collection do
      get 'signin_success'
      get 'signout_success'
    end
  end

  root :to => 'site#index'

  match ':controller(/:action(/:id))(.:format)'
end

app/controllers/site_controller.rb
# controller for 'static' web pages that comprise the site vs. the application 

class SiteController < ApplicationController
  
  def index
  end

  def info
  end

  def signin
  end
  
  def privacy
  end 
  
  def faq
  end
  
  def blog
  end
  
  def about
  end
     
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/about.html.erb
<div id="content">
<p>#todo</p>
</div>

app/views/site/blog.html.erb
<div id="content">
<p>#todo</p>
</div>

app/views/site/duckhome.html.erb
<!DOCTYPE html>
<html>
<head>
  
<%= stylesheet_link_tag 'site' %>

</head>
<body>

<div id="top">
  <div id="duck-logo"><%= image_tag 'duck-logo.png', :size => '150x150', :alt => 'duck-logo' %></div>
  <p style="font-size:3.0em; line-height:.75em;">Deal<span class="duck-span">duck</span></br><span style="font-size:.7em; color:#d0baa0;">Sales Forecast+Risk Analytics</span></p>
  
  <p>Why a duck?</p>
  <p>A "duck" is a small stack of stones guiding hikers on a hard to find trail. Like a trail duck, Deal<span class="duck-span">duck</span> Sales Forecast+Risk Analytics guides sales executives to make better forecasts, with less risk of missing.</p>
  <p>Sales executives are good at understanding and managing the uncertainties and risks of individual deals. However, when a sales pipeline includes dozens or hundreds of deals it is nearly impossible to quantify and manage the total risk of meeting or missing a forecast.</p><p>Until now. </p>
  <p>Deal<span class="duck-span">duck</span> gives valuable insight about the total risk in a forecast by looking at all deals that comprise a sales pipeline.
  <p>How good is your forecast? Wouldn't you like to know?</p>

  
    <br />
    <div id="more-info"><%= link_to 'Get more info', :controller => 'site', :action => 'duckinfo' %></div>
    <div id="sign-in"><%= link_to 'Users sign in', :controller => 'site', :action => 'ducksignin' %></div>
    <br />
</div>

<div style="margin-left:auto; margin-right:auto; width:750px; ">
  <table style="margin-top:10px; ">
    <tr>
      <td id="textbox">
        <strong>Lorem ipsum dolor sit amet</strong></br>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
      <td>
      <td style="width:20px;"></td>
      <td id="textbox">
        <strong>Lorem ipsum dolor sit amet</strong></br>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
      <td>
      <td style="width:20px;"></td>
      <td id="textbox">
        <strong>Lorem ipsum dolor sit amet</strong></br>Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam
      <td>
  </table>
  <br />
</div>

<div id="bottom" style="width:750; margin-left:auto; margin-right:auto;">
  <div style="copyright">
    <p>Copyright &copy; David Spenhoff. All rights reserved.</p>
  </div>
  
</div>

</body>
</html>

app/views/site/duckinfo.html.erb
<!DOCTYPE html>
<html>
<head>
  
<%= stylesheet_link_tag 'site' %>

</head>
<body>

<div id="top">
  <div id="duck-logo"><%= image_tag 'duck-logo.png', :size => '150x150', :alt => 'duck-logo' %></div>
  <p style="font-size:3.0em; line-height:.75em;">Deal<span class="duck-span">duck</span></br><span style="font-size:.7em; color:#d0baa0;">Sales Forecast+Risk Analytics</span></p>
  <p style="font-size:1.25em; line-height:1.4em;">Tell us the best way to connect so we can tell you more about Deal<span class="duck-span">duck<span>.</p>
<div>
  
  </br></br><p>#todo</p>
  

<div id="submit"><%= link_to 'Submit', 'duckhome' %></div>
</br>

<div id="bottom" style="width:750; margin-left:auto; margin-right:auto;">
  <div style="copyright">
    <p>Copyright &copy; David Spenhoff. All rights reserved.</p>
  </div>
  
</div>

</body>
</html>

app/views/site/ducksignin.html.erb
<!DOCTYPE html>
<html>
<head>
  
<%= stylesheet_link_tag 'site' %>

</head>
<body>

<div id="top">
  <div id="duck-logo"><%= image_tag 'duck-logo.png', :size => '150x150', :alt => 'duck-logo' %></div>
  <p style="font-size:3.0em; line-height:.75em;">Deal<span class="duck-span">duck</span></br><span style="font-size:.7em; color:#d0baa0;">Sales Forecast+Risk Analytics</span></p>
  <p style="font-size:1.25em; line-height:1.4em;">Registered users, please sign in.</p>
<div>
  
  </br></br><p>#todo</p>

<div id="submit"><%= link_to 'Submit', home_index_path %></div>
</br>

<div id="bottom" style="width:750; margin-left:auto; margin-right:auto;">
  <div style="copyright">
    <p>Copyright &copy; David Spenhoff. All rights reserved.</p>
  </div>
  
</div>

</body>
</html>

app/views/site/faq.html.erb
<div id="content">
<p>#todo</p>
</div>

app/views/site/index.html.erb
<div id="content">  
  <p>Why a duck?</p>
  <p>A "duck" is a stack of stones guiding hikers on a hard to find trail. Similarly, Deal<span class="duck-span">duck</span> guides sales executives to make better forecasts, with less risk of missing.</p>
  <p>Sales executives are good at understanding and managing the uncertainties and risks of individual deals. However, when a sales pipeline includes dozens or hundreds of deals it is nearly impossible to quantify and manage the total risk of meeting or missing a forecast.</p><p>Until now. </p>
  <p>Deal<span class="duck-span">duck</span> performs in-depth analysis and gives valuable insights about the total risk in a forecast by "crunching the numbers" across all deals in the sales pipeline.
  <p>How good is your forecast? What would you do if you knew?</p>

  
    <br />
    <div id="more-info"><%= link_to 'Get more info', :controller => 'site', :action => 'info' %></div>
    <div id="sign-in"><%= link_to 'Users sign in', :controller => 'sessions', :action => 'new' %></div>
    <br />
</div>

<div style="margin-left:auto; margin-right:auto; width:750px; padding-top:20px;">
  <table>
    <tr>
      <td id="textbox">
        <headline>Evaluate forecast risk</headline></br>
        <p>Deal<span class="duck-span">duck</span> lets you understand and manage the total risk in your forecast.<p>
      </td>
      <td style="width:20px;"></td>
      <td id="textbox">
        <headline>Test alternate scenarios</headline></br>
        <p>What-if analysis of alternate risk scenarios is fast and easy with Deal<span class="duck-span">duck</span>.</p>
      </td>
      <td style="width:20px;"></td>
      <td id="textbox">
        <headline>Manage "revenue at risk"</headline></br>
        <p>Are you likely to miss your forecast? How much? What would you do if you knew?</p>
      </td>
    </tr>
  </table>
  <br />
</div>

app/views/site/info.html.erb
<div id="content">
  <p style="font-size:1.25em; line-height:1.4em;">Tell us the best way to connect so we can tell you more about Deal<span class="duck-span">duck<span>.</p>
    
  </br></br><p>#todo</p>
</div>
  
<div id="submit"><%= link_to 'Submit', :controller => 'site', :action => 'index' %></div>
</br>

app/views/site/privacy.html.erb
<div id="content">    
    <h1>Privacy Policy</h1>
    <p>We have created this Privacy Policy to let you know what information we collect when you visit our website, why we collect it and how it is used.</p>
    <h3><strong>Information that we collect</strong></h3>
    <p>You may visit our website anonymously. However, when you register on our website, place an order, download a product, subscribe to our newsletter, respond to a survey or fill out a form, as appropriate you may be asked to enter your name, e-mail address, mailing address, phone number or credit card information as a condition of receiving the requested product, information or service. </p>
    <h3><strong>How we use your information</strong></h3>
    <p>Your information may be used in one of the following ways: </p>
    <p><i>To improve customer service.</i> Your information helps us to more effectively respond to your customer service requests and support needs.</p>
    <p><i>To process transactions.</i> Your information may be required to complete a specific transaction.</p>
    <p><i>To send periodic emails.</i> We may send emails to you from time to time describing our products and services or providing other information about us. Except for emails that are sent directly to you individually by one of our employees, all emails we send will include the ability for you to unsubscribe from future emails. Even if you unsubscribe, we may continue to send you emails that are necessary to communicate with you about your existing license, subscription, service, support and/or expressed interest for one of our products.</p>
    <h3><strong>How we protect your information</strong></h3>
<p>We use a variety of standard measures to protect the security of your personal information. All sensitive/credit information you provide us is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our payment gateway provider’s database and can only be accessed by authorized individuals.</p>
  <h3><strong>Cookies</strong></h3>
  <p>We do not use cookies.</p>
  <h3><strong>Disclosures to outside parties</strong></h3>
  <p>We will not sell, trade, or otherwise transfer to outside parties your personal information. This does not include trusted third parties who assist us in operating our website, conducting our business, or providing services to you, so long as those parties agree to keep your information confidential. </p>
  <h3><strong>Children</strong></h3>
  <p>Our website, products and services are all intended for people who are 13 years of age or older. By providing your information to us you represent that you are 13 years of age or older.</p>
  <h3><strong>Your Consent</strong></h3>
  <p>By using our website, you consent to this Privacy Policy</p>
  <h3><strong>Changes to our Privacy Policy</strong></h3>
  <p>If we decide to change our privacy policy, we will post those changes on this page and update the Privacy Policy modification date below. </p>
  <p>This Privacy Policy was last modified on September 15, 2013</p>
</div>  

app/views/site/signin.html.erb
<p id="notice"><%= flash[:notice] %>&nbsp;</p>

<div id="content">
  <h3>Registered users, please sign in.</h3>
<div>
			
<%=	form_tag sessions_path do %>
<table>
	<tr><td>Username &nbsp;</td><td><%= text_field_tag 'username' %></td></tr>
	<tr><td>Password &nbsp;</td><td><%= password_field_tag 'password' %></td></tr>
</table>
<p><%= submit_tag 'Sign In' %></p>
<% end %>


</br>